[[chapter2]]
== The C HAL API

=== General Principles

==== Discovery of Fixed Platform Characteristics at Run-time

Since we assume that code is built for a specific platform, it is undesirable to use function-calls (rather than
macros) to discover fixed platform characteristics; since this constitutes an unnecessary overhead.  However, there
may be circumstances where a BSP implementation wishes to supply code for this purpose.  For this reason, APIs for discovery
of some fixed platform characteristics have been implemented to look like a function call.  The assumption is that
in most cases these function calls can be optimized out by the compiler, leaving no overhead.

==== Distribution in Binary or Source Code Form

BSPs may be supplied either as source code, which the user builds into their system, or as a pre-built binary library.
To support the latter case, pre-processor directives that are intended to change BSP behaviour (as listed in
<<Global Definitions Set By Application Writers>>) must only be used in header files, not within the compiled C-code.

==== Thread Safety

All API functions shall be implemented in a way that supports simultaneous calls from multiple cores or software threads.
This is supported through the use of an initialisation function which allocates a separate context space for each instance.

=== Header File Structure

Application writers will include a single header file, *rvm_csi.h*, in their code where they wish to include RVM-CSI functionality.
This header is part of the API definition, and includes several further header files as follows:

[cols="2,1,5",options="header"]
|===
|Header|Supplied by|Contents
|csi_defs.h|API|Definitions which may be used by the BSP-supplied headers (such as return codes etc.)
|csi_bsp_csrs.h|BSP|CSR definitions
|csi_bsp_perip.h|BSP|Peripheral register definitions
|csi_bsp_interrupts.h|BSP|Enumeration of standard interrupt sources in the system
|csi_bsp_defs.h|BSP|Other macros supplied by the BSP, including macro definitions feeding into the inline functions within csi.h
|csi.h|API|Defines the HAL API itself. This is included last as it picks up definitions from the other files.  Note that
this header in turn includes other headers corresponding to different areas of functionality within the API.
|===

All header files must be protected against multiple inclusion, by means of a define which takes the form of a capitalised version
of the file name, with special characters replaced by underscores, and prefixed by double underscores.  For example a header file
csi_bsp_csrs.h will have contents of the form:
[source, c]
----
#ifndef __CSI_BSP_CSRS_H__
#define __CSI_BSP_CSRS_H__

// ... file contents

#endif // __CSI_BSP_CSRS_H__
----

=== Definitions set by BSPs

The following macros must be defined by BSP authors and exposed in the specified header files:

==== Context Size

csi_bsp_defs.h will define CSI_CONTEXT_SIZE_BYTES which specifies the required size of context to be passed into the csi_init()
function, in bytes.

==== CSRs (Control and Status Registers)

Standard RISC-V CSRs are defined in https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/encoding.h.
The appropriate version of this file for the platform should be supplied in the BSP and
included from csi_bsp_csrs.h.  In addition, csi_bsp_csrs.h should ennumerate all custom CSR names, addresses and bit-fields as follows:

TODO

==== Peripheral Registers

csi_bsp_perip.h should ennumerate all peripheral register names, addresses and bit-fields as follows:

TODO

==== Interrupts

csi_defs.h enumerates a set of standard interrupt sources as follows:

TODO

csi_bsp_interrupts.h should ennumerate all platform-specific interrupts in the system, giving them unique identification numbers
that follow on from the interrupt numbers in csi_defs.h, as follows:

TODO

=== Global Definitions Set By Application Writers

The following macros may be defined globally by application writers, in order to change the behaviour of the underlying BSP code:

[cols="3,2,6",options="header"]
|===
|Macro|Possible values|Purpose
|CSI_UPRINT_OUTPUT|NONE / SEMIHOST / UART / CIRCBUFF
a|Determines the text output mode of the csi_uprintf function.

* NONE=function has no effect;
* SEMIHOST=function routes to semihosting if available;
* UART=function routes to UART;
* CIRCBUF=function routes to circular buffer.

See csi_uprintf description for details.  If the macro is undefined,
behaviour defaults to SEMIHOST, in which case behaviour is undefined if a semihosting mechanism is unavailable.
|CSI_LOG_LEVEL|ERR / WARN / INFO / NONE|Determines the behaviour of the macros CSI_LOG_ERR, CSI_LOG_WARN and
CSI_LOG_INFO.  See documentation of these macros for details.
|===
