[[intro]]
== Introduction

RVM-CSI (Risc-V eMbedded - Common Software Interface) has been defined with the aim of facilitating the portability
of source code across different embedded platforms.

RVM refers to a class of _platforms_ and _profiles_ which RISC-V International intends to define.  A _profile_ defines a
specific base ISA, plus ISA extensions and any options applicable within those ISA extensions.  A _platform_ comprises
a profile plus further specifications for non-ISA features (such as interrupt controllers etc.).

Although no RVM platform or profile has yet been specified at time of writing, the initial specification of RVM-CSI
will have no dependency on certain features being present in the platform (beyond the base ISA).  Any run-time
functionality that depends on certain hardware characteristics can either a) report the absence of the required
functionality and hence be non-functional, or b) emulate the required functionality in software.

Therefore, a single Common Software Interface should serve to cover all defined RVM platforms going forward.

In constructing systems for RVM platforms, we assume the following:

* The software is built for a specific platform (i.e., platform characteristics are known at build time).
* The software is not using a rich OS such as linux (which would have its own standardised methods for control of
the platform and discovery of its characteristics).

This contrasts with the RVA platforms for application processors, where there is a requirement for _binary_ portability
of software between platforms (which in turn implies run-time discovery of platform characteristics).

Most importantly, RVM-CSI Specifies:

* The API (Application Programming Interface) for a _Hardware Abstraction Layer_ (HAL).  Board vendors can produce
_Board Support Packs_ (BSPs) conforming to this API, and application writers can write their code against the interface
in order to create portable code.
* The format of Board Support Packs.

While the first version of the specification deals with a C language API, future enhancements may encompass other
languages.  Implementations in different languages will share common function names and descriptions wherever possible.

=== Definitions

* RVM-CSI *_API definition_*: a language-specific, platform-agnostic programming interface that is used by
application writers. indexterm:[API definition]
* *_Application writers_*: users of the API, writing code which is portable between platforms.
indexterm:[Application Writers]
* *_Board Support Pack_* (BSP): a package containing the platform-specific code implementing the
functionality in the API. (This could also be implemented within a language runtime). indexterm:[Board Support Pack]
indexterm:[BSP]

=== Assumed Features of Underlying Hardware

==== Privilege Levels

We assume that systems targeted by RVM-CSI will require either Machine-mode only, or Machine mode + User mode.
No functionality is provided to target Hypervisor, Supervisor or VS privilege modes.

==== Virtual Memory

RVM-CSI does not support virtual addressing.
